#define COMPONENT logistics
#include "\z\stx\addons\main\script_mod.hpp"

//#define DEBUG_MODE_FULL
//#define DISABLE_COMPILE_CACHE

#ifdef DEBUG_ENABLED_LOGISTICS
	#define DEBUG_MODE_FULL
#endif
	#ifdef DEBUG_SETTINGS_LOGISTICS
	#define DEBUG_SETTINGS DEBUG_SETTINGS_LOGISTICS
#endif

#include "\z\stx\addons\main\script_macros.hpp"
#include "\a3\ui_f\hpp\definedikcodes.inc"
#include "\a3\ui_f_curator\ui\defineresincldesign.inc"

#define MAX_LOAD 9999999

#define PLACE_WAITING 	-1
#define PLACE_CANCEL 	0
#define PLACE_APPROVE 	1

#define IDC_TITLE 		1
#define IDC_BG 			2
#define IDC_CLOSE 		3
#define IDC_CONFIRM 	4
#define IDC_GROUP 		5

#define IDC_HUB_EDITINV_TEXT 					100
#define IDC_HUB_EDITINV 						101
#define IDC_HUB_BOXSPAWN_TEXT 					102
#define IDC_HUB_BOXSPAWN 						103
#define IDC_HUB_CANTEEN_TEXT 					104
#define IDC_HUB_CANTEEN 						105
#define IDC_HUB_CONSTRUCTION_TEXT 				106
#define IDC_HUB_CONSTRUCTION 					107
#define IDC_HUB_CONSTRUCTION_SIDE_TEXT 			108
#define IDC_HUB_CONSTRUCTION_SIDE 				109
#define IDC_HUB_ARSENAL_TEXT 					110
#define IDC_HUB_ARSENAL 						111
#define IDC_HUB_WHITELIST_TEXT 					112
#define IDC_HUB_WHITELIST 						113
#define IDC_HUB_WHITELIST_EDIT 					114
#define IDC_HUB_BLACKLIST_TEXT 					115
#define IDC_HUB_BLACKLIST 						116
#define IDC_HUB_BLACKLIST_EDIT 					117

#define IDC_RESUPPLY_APPLICATION_TEXT 			100
#define IDC_RESUPPLY_APPLICATION 				101
#define IDC_RESUPPLY_APPLICATION_BG 			102
#define IDC_RESUPPLY_APPLICATION_GROUP 			103
#define IDC_RESUPPLY_BOX_CLASS_TEXT 			104
#define IDC_RESUPPLY_BOX_CLASS 					105
#define IDC_RESUPPLY_BOX_CLASS_PICKER 			106
#define IDC_RESUPPLY_CARGO_TYPE_TEXT 			107
#define IDC_RESUPPLY_CARGO_TYPE 				108
#define IDC_RESUPPLY_UNLOAD_TIME_TEXT 			109
#define IDC_RESUPPLY_UNLOAD_TIME 				110
#define IDC_RESUPPLY_UNLOAD_TIME_EDIT 			111
#define IDC_RESUPPLY_HEIGHT_TEXT 				112
#define IDC_RESUPPLY_HEIGHT 					113
#define IDC_RESUPPLY_SIGNALS_TEXT 				114
#define IDC_RESUPPLY_SIGNAL1 					115
#define IDC_RESUPPLY_SIGNAL2 					116
#define IDC_RESUPPLY_SIDE_TEXT 					117
#define IDC_RESUPPLY_SIDE 						118
#define IDC_RESUPPLY_FACTION_TEXT 				119
#define IDC_RESUPPLY_FACTION 					120
#define IDC_RESUPPLY_CATEGORY_TEXT 				121
#define IDC_RESUPPLY_CATEGORY 					122
#define IDC_RESUPPLY_VEHICLE_TEXT 				123
#define IDC_RESUPPLY_VEHICLE 					124
#define IDC_RESUPPLY_CONTENTS_TEXT 				125
#define IDC_RESUPPLY_CONTENTS 					126
#define IDC_RESUPPLY_CONTENTS_BG 				127
#define IDC_RESUPPLY_CONTENTS_GROUP 			128
#define IDC_RESUPPLY_CAPACITY_LIMIT_TEXT 		129
#define IDC_RESUPPLY_CAPACITY_LIMIT 			130
#define IDC_RESUPPLY_EDIT_INV 					131
#define IDC_RESUPPLY_PRESETS_CATEGORY_TEXT 		132
#define IDC_RESUPPLY_PRESETS_CATEGORY 			133
#define IDC_RESUPPLY_PRESETS_TEXT 				134
#define IDC_RESUPPLY_PRESETS 					135
#define IDC_RESUPPLY_PRESETS_NAME_TEXT 			136
#define IDC_RESUPPLY_PRESETS_NAME 				137
#define IDC_RESUPPLY_PRESETS_SAVE 				138
#define IDC_RESUPPLY_PRESETS_RENAME 			139
#define IDC_RESUPPLY_PRESETS_LOAD 				140
#define IDC_RESUPPLY_PRESETS_DELETE 			141
#define IDC_RESUPPLY_WHITELIST_TEXT 			142
#define IDC_RESUPPLY_WHITELIST 					143
#define IDC_RESUPPLY_WHITELIST_EDIT 			144
#define IDC_RESUPPLY_BLACKLIST_TEXT 			145
#define IDC_RESUPPLY_BLACKLIST 					146
#define IDC_RESUPPLY_BLACKLIST_EDIT 			147
#define IDC_RESUPPLY_MUNITIONS 					148
#define IDC_RESUPPLY_MEDICAL 					149
#define IDC_RESUPPLY_MAGAZINE_COUNT_TEXT 		150
#define IDC_RESUPPLY_MAGAZINE_MULTIPLY 			151
#define IDC_RESUPPLY_MAGAZINE_COUNT 			152
#define IDC_RESUPPLY_MAGAZINE_COUNT_EDIT 		153
#define IDC_RESUPPLY_UNDERBARREL_COUNT_TEXT 	154
#define IDC_RESUPPLY_UNDERBARREL_MULTIPLY 		155
#define IDC_RESUPPLY_UNDERBARREL_COUNT 			156
#define IDC_RESUPPLY_UNDERBARREL_COUNT_EDIT 	157
#define IDC_RESUPPLY_ROCKET_COUNT_TEXT 			158
#define IDC_RESUPPLY_ROCKET_MULTIPLY 			159
#define IDC_RESUPPLY_ROCKET_COUNT 				160
#define IDC_RESUPPLY_ROCKET_COUNT_EDIT 			161
#define IDC_RESUPPLY_THROWABLE_COUNT_TEXT 		162
#define IDC_RESUPPLY_THROWABLE_MULTIPLY 		163
#define IDC_RESUPPLY_THROWABLE_COUNT 			164
#define IDC_RESUPPLY_THROWABLE_COUNT_EDIT 		165
#define IDC_RESUPPLY_PLACEABLE_COUNT_TEXT 		166
#define IDC_RESUPPLY_PLACEABLE_MULTIPLY 		167
#define IDC_RESUPPLY_PLACEABLE_COUNT 			168
#define IDC_RESUPPLY_PLACEABLE_COUNT_EDIT 		169
#define IDC_RESUPPLY_MEDICAL_COUNT_TEXT 		170
#define IDC_RESUPPLY_MEDICAL_MULTIPLY 			171
#define IDC_RESUPPLY_MEDICAL_COUNT 				172
#define IDC_RESUPPLY_MEDICAL_COUNT_EDIT 		173
#define IDC_RESUPPLY_BOX_CLASS_TREE 			174
#define IDC_RESUPPLY_UNITS_TEXT 				175
#define IDC_RESUPPLY_UNITS_TOOLBOX 				176
#define IDC_RESUPPLY_UNITS_LISTBOX 				177
