name = "Simplex Tools and Extensions"
mainprefix = "z"
prefix = "stx"
author = "Simplex Team"

[files]
include = [
    "mod.cpp",
    "assets/stx.paa",
    "LICENSE",
    "authors.txt"
]

[version]
major = 0
minor = 3
patch = 7
git_hash = 0
